on:
    # Only manual for the time beig
    workflow_dispatch:
name: Deploy on push
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get content
              uses: actions/checkout@master

            - name: Sync files
              uses: wlixcc/SFTP-Deploy-Action@v1.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port : ${{secrets.FTP_PORT}}
                  remote_path: ${{secrets.FTP_PATH}}
