on:
    # Only manual for the time beig
    workflow_dispatch:
name: Deploy to SFTP
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get content
              uses: actions/checkout@master

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port : ${{secrets.FTP_PORT}}
                  server-dir: ${{secrets.FTP_PATH}}
